export const PERFORMER_STATUSES = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  PENDING: 'pending-email-confirmation'
};

export const PERFORMER_CHANNEL = 'PERFORMER_CHANNEL';

export const PERFORMER_UPDATE_STATUS_CHANNEL = 'PERFORMER_UPDATE_STATUS_CHANNEL';

export const DELETE_PERFORMER_CHANNEL = 'DELETE_PERFORMER_CHANNEL';

export const ACTIVE_PERFORMER_IDS_CACHE = 'ACTIVE_PERFORMRES';
export const INACTIVE_PERFORMER_IDS_CACHE = 'INACTIVE_PERFORMRES';
export const PENDING_PERFORMER_IDS_CACHE = 'PENDING_PERFORMRES';
